### PR TITLE
[WIP] Added experience system

### PR DESCRIPTION
**Pull request by PureTryOut**
Still a WIP, made the PR so you guys can see how the work is going.

This implements the [experience system](http://minecraft.gamepedia.com/Experience). By digging blocks, smelting items (not yet implemented), and later killing mobs or fishing, experience orbs will be dropped. If a player is close enough (6 meter), these orbs will float towards the player and once close enough, be collected (the closest player to the orb when it doesn't have a target yet is chosen as new target). The orbs disappear and the amount of experience that they hold is added to the player. The level is calculated by a formula from the Minecraft Gamepedia using the experience the player has.

I also made API functions which can be used by other mods to either add experience, or subtract it when for example enchanting a weapon.

The level and experience required till the next level are also shown on the hud.
screenshot_2017-02-12_21-58-12

### CODE REVIEW

**Comment by Avamander** [comment]
Haven't had the time to test this out but two small questions.
1. What happens when there's a lot of XP? Lagfest or not?
3. Does the XP circle the player like in MC?

**Comment by PureTryOut** [comment]
1. Lots of orbs you mean? It's quite hard to get a lot of them, as the total experience that are dropped is spread over certain sizes of orbs. The bigger the experience, the bigger the (singular) orb. I use a regular entity so I guess it would cause just as much lag as dropped items would, probably not much but will have to be tested indeed.
2. Not yet. Right now they are instantly added to the player if they reach them, where as in Minecraft they wait for each other, but the rate of which doesn't seem to be known. I guess we'll have to add a delay of 0.2 seconds or something.
3. I rather not yet add those to be honest, those would be part of a bigger "brewing PR". Right now I just set the experience drop rate of coal to whatever I need for testing.

**Comment by Avamander** [comment]
3. In MC XP potions were added before brewing was. So it'd be fine just to make sure the feature works.

**Comment by PureTryOut** [comment]
Well we don't have to follow Minecraft in stuff like that ;) Like I said, I just set the experience drop rate of coal to whatever, you could do the same for testing. I'll look into a potion though.

**Comment by PureTryOut** [comment]
Merging without the potion. Although I do remember there being an experience potion in the past, [the gamepedia doesn't actually mention it anywhere](http://minecraft.gamepedia.com/Potion). To "use" this feature just mine some coal, diamond or lapis ore.

**Comment by Avamander** [comment]
@PureTryOut http://minecraft.gamepedia.com/Bottle_o%27_Enchanting

**Comment by PureTryOut** [comment]
Completely missed that ;) Will add it in an upcoming PR. Will probably be drinking at first though.

**Pull request merged**
